### ISSUE TITLE
Only news listing, no items opening

### ISSUE THREAD

**Issue by enzlinux** [SanderKlootwijk/ubuntu-nednieuws#2]
Unfortunately is has stopped working good since version 2.2.
News list opens fine but when clicking one of the news items I get an empty screen. Happens on my BQ E5, BQ E10 and FP2.

**Comment by SanderKlootwijk** [comment]
Thank you for submitting this bug report. I found the problem. I tested the app on my Pixel 3a, which runs on the latest RC version of Ubuntu Touch. The update works great on this version, but the latest OTA (23) does indeed show an empty article page, with the 2.2 update of NedNieuws. This is because I'm using navigationHistory.clear() on the webview. Apparently this is not yet supported in OTA 23, but it is already on the latest RC. With a next OTA update, I will test the changes again. Until then a working version is in the store (2.2.1), which works on the latest OTA. Thanks again for reporting :)
